### ISSUE TITLE
Instructor Feedback - Week 4 Exercise

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [HolliNiesen/AmazingArea#1]
Wow! Looks like you have a great start on one-to-many as well! 

-  [x] Will you need to do any searches other than by first name? Maybe a method like findByProperty would be more flexible, allowing a search by any column and value? https://github.com/HolliNiesen/AmazingArea/blob/f08fb0e3278e3c5ad3eae30eb5c764af9941f56a/src/main/java/com/mathtasticgames/persistence/UserDao.java#L79
- [x] Take a peek at the start to the  generic dao code that I put out in #hibernate in slack. It's likely you'll be able to use that single dao for everything!

**Comment by HolliNiesen** [comment]
Generic DAO is done (and I love it)! All specific searches have been replaced with getByProperty()
