### ISSUE TITLE
Design & Code review

### ISSUE THREAD

**Issue by jacquesmatcgithub** [HolliNiesen/AmazingArea#3]
# Design/Code Review 1

### Reviewer: Jacques Fourie

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| Your problem statement described your project very well. It is clearly written making it very easy to understand. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | Your screen design was great. It was super easy to follow and the colorful design is going to be great for your target audience. Great job on that.  |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| Your databse deign reflected your screen design. Just like my database design I got the feeling you are also still mulling over the design to some extent. You satisfied the one-to-many requirement and I liked your clean straight forward approach. |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages. | Unfortunately we did not get into the code too much because of time constraints, but you are using a proper Maiven project layout and I noticed you did have several JSPs in the works.

**Comment by pawaitemadisoncollege** [comment]
@jacquesmatcgithub Did you check for System.out.println statements?
